//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyor3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdministrasiDBEntities : DbContext
    {
        public AdministrasiDBEntities()
            : base("name=AdministrasiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Guru> Guru { get; set; }
        public virtual DbSet<Mapel> Mapel { get; set; }
        public virtual DbSet<Nilai> Nilai { get; set; }
        public virtual DbSet<Siswa> Siswa { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
