//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyor3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nilai
    {
        public int id { get; set; }
        public string kodeMapel { get; set; }
        public string nis { get; set; }
        public string nip { get; set; }
    
        public virtual Guru Guru { get; set; }
        public virtual Mapel Mapel { get; set; }
        public virtual Siswa Siswa { get; set; }
    }
}
